# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_auto_20170925_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('roleid', models.UUIDField(default=uuid.UUID('c73f113e-fc1e-43ed-8a63-af93a4550064'), editable=False, primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=50)),
                ('roledesc', models.CharField(max_length=255)),
                ('createts', models.DateTimeField(auto_now_add=True)),
                ('updatets', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='articals',
            table='articals',
        ),
        migrations.AlterModelTable(
            name='blogtags',
            table='artical_tags',
        ),
    ]
