# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_auto_20170926_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRRoles',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createts', models.DateTimeField(auto_now_add=True)),
                ('updatets', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user_r_roles',
            },
        ),
    ]
